[app]

# (Required) Title of your application
title = OffloadApp

# (Required) Package name
package.name = offloadapp

# (Required) Package domain (reverse DNS style)
package.domain = org.example

# Source code location
source.dir = .
source.include_exts = py,kv
source.exclude_exts = spec
source.include_patterns = assets/*,images/*.png
source.exclude_dirs = tests, bin

# Versioning
version = 1.0
android.version_code = 1

# Application requirements
requirements = python3,kivy,flask,requests,psutil,zeroconf,cython

# Orientation
orientation = portrait

# Bootstrap (sdl2 is the recommended one)
bootstrap = sdl2

# Supported architectures
android.archs = armeabi-v7a, arm64-v8a

# Android API levels
android.minapi = 21
android.api = 30
android.compile_sdk = 30
android.build_tools_version = 30.0.3

# Icon and Presplash
icon.filename = %(source.dir)s/icon.png
presplash.filename = %(source.dir)s/presplash.png

# Permissions
android.permissions = INTERNET

# Optional SQLite3
android.sqlite3 = True

# Entry point
android.entrypoint = org.kivy.android.PythonActivity

# Logging level (0=debug, 2=warning)
log_level = 2

# Prevent deploy and run after build
deploy = 0
run = 0
