name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git \
               libffi-dev libssl-dev zlib1g-dev libsqlite3-dev

      - name: Install Buildozer & Cython
        run: |
          pip3 install --user buildozer cython

      - name: Add Buildozer to PATH
        run: echo "${{ runner.home }}/.local/bin" >> $GITHUB_PATH

      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          buildozer android debug --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: offloadapp-apk
          path: bin/*.apk
