name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java (JDK 8)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip build-essential git \
            libffi-dev libssl-dev zlib1g-dev libsqlite3-dev \
            ant openjdk-8-jdk-headless

      - name: Install Buildozer & Cython
        run: |
          pip3 install --user --upgrade buildozer cython

      - name: Add Buildozer to PATH
        run: echo "${{ runner.home }}/.local/bin" >> $GITHUB_PATH

      - name: Build APK
        working-directory: ${{ github.workspace }}
        run: |
          buildozer android debug --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: offloadapp-apk
          path: bin/*.apk
