name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java (JDK 11)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Set up Android SDK & Build Tools
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: "30.0.3"
          ndk: "23.1.7779620"

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git libffi-dev libssl-dev zlib1g-dev

      - name: Install Buildozer & Cython
        run: |
          pip3 install --user --upgrade buildozer cython

      - name: Add Buildozer to PATH
        run: echo "${{ runner.home }}/.local/bin" >> $GITHUB_PATH

      - name: Build APK
        working-directory: ${{ github.workspace }}
        run: |
          buildozer android debug --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: offloadapp-apk
          path: bin/*.apk
