name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ANDROID_SDK_ROOT: ${{ runner.home }}/android-sdk
  ANDROID_HOME: ${{ runner.home }}/android-sdk
  PATH: ${{ runner.home }}/android-sdk/cmdline-tools/latest/bin:${{ runner.home }}/android-sdk/platform-tools:${{ runner.path }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java (JDK 8)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip build-essential git \
            libffi-dev libssl-dev zlib1g-dev \
            wget unzip

      - name: Install Android SDK command-line tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          unzip tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          rm tools.zip

      - name: Accept SDK licenses & install SDK components
        run: |
          yes | sdkmanager --sdk_root=${ANDROID_SDK_ROOT} --licenses
          sdkmanager --sdk_root=${ANDROID_SDK_ROOT} \
            "platform-tools" \
            "platforms;android-30" \
            "build-tools;30.0.3"

      - name: Install Buildozer & Cython
        run: |
          pip3 install --user --upgrade buildozer cython

      - name: Add Buildozer to PATH
        run: echo "${{ runner.home }}/.local/bin" >> $GITHUB_PATH

      - name: Build APK
        working-directory: ${{ github.workspace }}
        run: |
          buildozer android debug --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: offloadapp-apk
          path: bin/*.apk
