name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git \
               libffi-dev libssl-dev zlib1g-dev libsqlite3-dev
          pip3 install --user buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build APK
        run: |
          buildozer android debug --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: offloadapp-apk
          path: bin/*.apk
